(import (chicken blob)
        (chicken random)
        (chicken condition)
        (srfi-4))

(define (generate-zero-key key-bits)
  (let ((vec (make-u8vector (/ key-bits 8) 0)))
    vec))

(define (generate-random-key key-bits)
  (let* ((len (/ key-bits 8))
         (buf (make-blob len)))
    (blob->u8vector/shared (random-bytes buf len))))

(define (stream-cipher key nonce ctr in-fd out-fd)
  (let* ((key-bits (* 8 (u8vector-length key)))
         (len (foreign-stream-cipher key key-bits nonce ctr in-fd out-fd)))
    (unless (< 0 len)
      (signal (condition '(exn location stream-cipher)
                         `(ret ,len))))
    len))
