version: 2
jobs:
  build:
    docker:
      - image: buhman/chicken:rijndael
    steps:
      - checkout
      - run:
          name: build
          command: |
            chicken-install -n
      - run:
          name: test
          command: |
            csi tests/run.scm
